# Sitewide configuration settings. Set `title` to the site title, which
# will be appended to the URL following {{page.title}} |

title: BSAN
auto: true
server: false
baseurl: /
# permalink: /:year/:month/:day/:title/
permalink: pretty
markdown: rdiscount
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock

siteurl: 'http://bsan.com.au'

flickr:
  api_key: 2ab246dcc6541ac08fa07f23b8027f85

paginate: 5

safe:        false
server_port: 4000

source:      .
destination: ./_site

future:      true
lsi:         false
pygments:    true

prose:
  siteurl: "http://bsan.com.au"
  media: "images"
  rooturl: "_posts/2013"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "post"

