title: BSAN
auto: true
server: false
baseurl: /
# permalink: /:year/:month/:day/:title/
permalink: pretty
markdown: rdiscount
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock

siteurl: 'http://bsan.com.au'

flickr:
  api_key: 2ab246dcc6541ac08fa07f23b8027f85

paginate: 5

safe:        false
server_port: 4000

source:      .
destination: ./_site

future:      true
lsi:         false
pygments:    true


prose:
  rooturl: '_posts'
  siteurl: 'http://bsan.com.au/'
  relativeLinks: ''
  media: 'images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Category"
          placeholder: "Choose Tags"
          options:
            - name: "Artist"
              value: "artist"
            - name: "Event"
              value: "event"
            - name: "Weekly"
              value: "weekly"
      - name: "image"
        field:
          element: "text"
          label: "Post image"
          value: ""
      - name: "detail"
        field:
          element: "text"
          label: "Detail"
          value: ""
          
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
