title: BSAN
baseurl: /
permalink: pretty
markdown: rdiscount
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock

siteurl: 'http://bsan.com.au'

flickr:
  api_key: 2ab246dcc6541ac08fa07f23b8027f85

paginate: 5

safe:        false
port: 4000

source:      .
destination: ./_site

future:      true
lsi:         false
pygments:    true

# Prose settings
prose:
  siteurl: 'http://darcemac.github.io/'
  relativeLinks: ''
  media: 'images'
