# Sitewide configuration settings. Set `title` to the site title, which
# will be appended to the URL following {{page.title}} |

title: BSAN
auto: true
server: false
baseurl: /
permalink: /:year/:month/:day/:title/
markdown: rdiscount
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock

siteurl: 'http://bsan.com.au'

flickr:
  api_key: 2ab246dcc6541ac08fa07f23b8027f85

paginate: 5

safe:        false
server_port: 4000

source:      .
destination: ./_site

future:      true
lsi:         false
pygments:    true

prose:
  rooturl: '_posts'
  siteurl: 'http://bsan.com.au/'
  relativeLinks: ''
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "category"
        field:
          element: "multiselect"
          label: "Add Category"
          placeholder: "Choose Category"
          options:
            - name: "Artist"
              value: "artist"
            - name: "Event"
              value: "event"
      - name: "genre"
        field:
          element: "multiselect"
          label: "Add Genre"
          placeholder: "Choose Genre"
          options:
            - name: "Acoustic"
              value: "acoustic"
            - name: "Rock"
              value: "rock"
            - name: "Blues"
              value: "blues"
            - name: "Jazz"
              value: "jazz"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - CURRENT_DATETIME: